### PR TITLE
fix the broken list autocomplete filter with django 3.2

### LINKED ISSUE #53: The change in Django 3.2 to consider limit_choices_to has broken this filter.
When opening the select, the choices don't show up due to this error:
```
'ManyToOneRel' object has no attribute 'get_limit_choices_to'
```

### PR DESCRIPTION
**Pull request by MDziwny**
fix #53

### CODE REVIEW

**Comment by MDziwny** [comment]
@farhan0581, could you tell me if you need something else to validate this PR?
I wanted to add a unit test but the test suite is not really user-friendly and I'm not really willing to spend too much time fixing it for django 3.2 :/

**Comment by n1k0** [comment]
@farhan0581 Hello, any idea when we can expect a new release including this fix? Thanks!

**Comment by jeffreybrowning** [comment]
Going to risk going against the emoji over +1 orthodoxy here, but 10 days is a bit long. 

> Hello, any idea when we can expect a new release including this fix?

**Comment by n1k0** [comment]
Hello @farhan0581, can we help you in any way to get this patch released?

**Comment by farhan0581** [comment]
Sorry for delay, but some personal emergency situation on my side, let me figure something out for the release.

**Comment by jeffreybrowning** [comment]
@farhan0581 I'm sorry to hear that. I hope everything is okay and you're doing alright.

**Pull request merged**
